/* Generated by Yosys 0.61+129 (git sha1 6dbe03f0f-dirty, aarch64-apple-darwin23.5-clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "up_counter.v:1.1-11.10" *)
module up_counter(clk, R);
  (* src = "up_counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "up_counter.v:4.12-4.13" *)
  output R;
  wire R;
  (* src = "up_counter.v:10.16-10.35" *)
  wire _00_;
  (* src = "up_counter.v:10.16-10.46" *)
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [7:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [7:0] _04_;
  (* src = "up_counter.v:3.15-3.20" *)
  reg [3:0] state = 4'h0;
  (* src = "up_counter.v:6.5-8.8" *)
  always @(posedge clk)
    state[0] <= _03_[0];
  (* src = "up_counter.v:6.5-8.8" *)
  always @(posedge clk)
    state[1] <= _04_[1];
  (* src = "up_counter.v:6.5-8.8" *)
  always @(posedge clk)
    state[2] <= _04_[2];
  (* src = "up_counter.v:6.5-8.8" *)
  always @(posedge clk)
    state[3] <= _04_[3];
  assign _03_[0] = ~state[0];
  assign _02_[1] = state[1] &(* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:293.27-293.63|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:240.19-240.41" *)  state[0];
  assign _00_ = state[3] &(* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:293.27-293.63|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:241.12-241.34" *)  state[2];
  assign _02_[2] = state[2] &(* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:293.27-293.63|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:248.19-248.41" *)  _02_[1];
  assign _01_ = _00_ &(* src = "up_counter.v:10.16-10.46" *)  state[1];
  assign R = _01_ &(* src = "up_counter.v:10.16-10.57" *)  state[0];
  assign _04_[1] = state[1] ^(* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:296.13-296.25" *)  state[0];
  assign _04_[2] = state[2] ^(* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:296.13-296.25" *)  _02_[1];
  assign _04_[3] = state[3] ^(* src = "up_counter.v:7.18-7.30|/Users/adityaln/Applications/oss-cad-suite/libexec/../share/yosys/techmap.v:296.13-296.25" *)  _02_[2];
  assign { _02_[7:4], _02_[0] } = { 4'h0, state[0] };
  assign _03_[7:1] = { 4'h0, state[3:1] };
  assign { _04_[7:4], _04_[0] } = { 3'h0, _02_[3], _03_[0] };
endmodule
